name: openworld
description: Openworld gaming engine using three_dart
version: 0.0.2
homepage: https://github.com/forthtemple/openworlddart

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  openworld_gl:
    git:
      #    #url: 'https://github.com/wasabia/flutter_gl'
      url: 'https://github.com/forthtemple/openworld_gl.git'
  http: ^1.1.0
  universal_html: ^2.2.4
  ffi: ^2.1.0
  image: ^4.0.02
  #flutter_gl: ^0.0.21
  typr_dart: ^0.0.2
  opentype_dart: ^0.0.1
  crypto: ^3.0.3
  audioplayers: ^6.1.0
  shared_preferences: ^2.2.3
  #openworld_gl: ^0.0.23
  archive: ^3.3.0
dependency_overrides:
  #openworld_gl:
  #  path: ../openworld_gl/openworld_gl
dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.0.3


flutter:
