name: secondtemple # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '0.2' # just for humans, typically '1.2+git' or '1.3.2'
summary: Explore the Second Temple # 79 char long summary
description: |
  You've been transported back to Jerusalem 70CE within the Second Temple. For over 600 years the ark of the covenant has been missing. Can you find the ark in time to save Jerusalem from the calamities to come? Game is completely offline so can play without internet though there is an online capability.
icon: snap/gui/secondtemple.png
website: https://github.com/forthtemple/openworlddart/tree/main/examplesecondtemple
source-code: https://github.com/forthtemple/openworlddart/tree/main/examplesecondtemple

grade: stable #devel # must be '' to release into candidate/stable channels
confinement: strict #devmode # use 'strict' once you have the right plugs and slots

apps:
  secondtemple:
    command: secondtemple
    extensions: [gnome]
    plugs:
      - opengl 

parts:
  secondtemple:
    source: .
    #source: ../../openworlddart/examplesecondtemple/
    source-type: local
    plugin: flutter
    flutter-target: lib/main.dart
    build-packages:
      - libgstreamer1.0-dev
      - libgstreamer-plugins-base1.0-dev
      - libglew-dev
      #- libglew-2.2
      #- libblas-dev 
      #- liblapack-dev
      - libatlas-base-dev
    stage-packages:
      - libgstreamer1.0-0
      - libgstreamer-plugins-base1.0-0
      - libglew2.2
      - libatlas3-base
      #- liblapack3
      #- libblas3
    organize:
      usr/lib/*-linux-gnu/blas/*: usr/lib/
      usr/lib/*-linux-gnu/lapack/*: usr/lib/
      usr/lib/*-linux-gnu/atlas/*: usr/lib/
#layout:
   #/usr/lib/x86_64-linux-gnu/libGLEW.so.2.2:
   #  bind: $SNAP_DATA/usr/lib/x86_64-linux-gnu/libGLEW.so.2.2
  #/usr/lib/x86_64-linux-gnu/libGLEW.so:
  #  bind: $SNAP_DATA/usr/lib/x86_64-linux-gnu/libGLEW.so     
  #/usr/lib/x86_64-linux-gnu/libGLEW.so:
  #  bind: $SNAP_DATA/usr/lib/x86_64-linux-gnu/libGLEW.so     
